name: file_uploader
services:
  mysql:
    image: mysql:8.4
    environment:
      - "MYSQL_ROOT_HOST=%"
      - "MYSQL_ROOT_PASSWORD=root"
    volumes:
      - file_uloader_sql:/var/lib/mysql
      - ./sql/init:/docker-entrypoint-initdb.d
      - ./sql/conf.d:/etc/mysql/conf.d
      - ./sql/log/slow.log:/tmp/slow.log
    ports:
      - "3307:3306"
    networks:
      - my-network
    
      

  otel-collector:
    image: otel/opentelemetry-collector-contrib
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - 4317:4317 # OTLP gRPC receiver

  prometheus: #tracer
    image: prom/prometheus:v2.52.0
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

  jaeger: # metrics
    image: jaegertracing/all-in-one:1.57
    ports:
      - 16686:16686

networks:
  my-network:

volumes:
  file_uloader_sql: