receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317 #TODO localhostに変更可能

processors:
  batch:

exporters:
  prometheus:
    endpoint: 0.0.0.0:9090

  otlp:
    endpoint: jaeger:4317
    tls:
      insecure: true

  debug:
    verbosity: detailed # 冗長性を持たせて出力, 設定なしだと標準出力？

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: []
      exporters: [prometheus, debug]
    traces:
      receivers: [otlp]
      processors: []
      exporters: [otlp, debug]
